# Name(s)
Alex Tschopp

**Instructions:** This is an individual assignment, but you may discuss your code with your neighbors.

# Python and NumPy

While other IDEs exist for Python development and for data science related activities, one of the most popular environments is Jupyter Notebooks.

This lab is not intended to teach you everything you will use in this course. Instead, it is designed to give you exposure to some critical components from NumPy that we will rely upon routinely.

## Exercise 0
Please read and reference the following as your progress through this course. 

* [What is the Jupyter Notebook?](https://nbviewer.jupyter.org/github/jupyter/notebook/blob/master/docs/source/examples/Notebook/What%20is%20the%20Jupyter%20Notebook.ipynb#)
* [Notebook Tutorial](https://www.datacamp.com/community/tutorials/tutorial-jupyter-notebook)
* [Notebook Basics](https://nbviewer.jupyter.org/github/jupyter/notebook/blob/master/docs/source/examples/Notebook/Notebook%20Basics.ipynb)

**In the space provided below, what are three things that still remain unclear or need further explanation?**

**YOUR ANSWER HERE**

## Exercises 1-7
For the following exercises please read the Python appendix in the Marsland textbook and answer problems A.1-A.7 in the space provided below.

## Exercise 1

In [16]:
import numpy as np
a = np.ones((6, 4), int) * 2
print(a)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


## Exercise 2

In [12]:
b = np.ones((6, 4), int) 
np.fill_diagonal(b, 3)
print(b)

[[3 1 1 1]
 [1 3 1 1]
 [1 1 3 1]
 [1 1 1 3]
 [1 1 1 1]
 [1 1 1 1]]


## Exercise 3

The '*' operator multiplies the arrays 'a' and 'b' element-wise while the function np.dot(a,b) requires the number of columns of 'a' to be equal to the number of rows of 'b'. The element-wise multiplication works because the matrices have the same shape and the dot product does not work because the shapes of the matrices are incompatible.

## Exercise 4

In [19]:
# YOUR SOLUTION HERE

## Exercise 5

In [ ]:
# YOUR SOLUTION HERE

## Exercise 6

In [ ]:
# YOUR SOLUTION HERE

## Exercise 7

In [ ]:
# YOUR SOLUTION HERE

## Exercise 8
Repeat exercise A.1 from Marsland, but create a Pandas DataFrame instead of a NumPy array.

In [ ]:
# YOUR SOLUTION HERE

## Exercise 9
Repeat exercise A.2 using a DataFrame instead.

In [ ]:
# YOUR SOLUTION HERE

## Exercise 10
Repeat exercise A.3 using DataFrames instead.

In [ ]:
# YOUR SOLUTION HERE

## Exercise 11
Repeat exercise A.7 using a dataframe.

In [ ]:
# YOUR SOLUTION HERE

## Exercises 12-14
Now let's look at a real dataset, and talk about ``.loc``. For this exercise, we will use the popular Titanic dataset from Kaggle. Here is some sample code to read it into a dataframe.

In [ ]:
titanic_df = pd.read_csv(
    "https://raw.githubusercontent.com/dlsun/data-science-book/master/data/titanic.csv"
)
titanic_df

Notice how we have nice headers and mixed datatypes? That is one of the reasons we might use Pandas. Please refresh your memory by looking at the 10 minutes to Pandas again, but then answer the following.

## Exercise 12
How do you select the ``name`` column without using .iloc?

In [ ]:
## YOUR SOLUTION HERE

## Exercise 13
After setting the index to ``sex``, how do you select all passengers that are ``female``? And how many female passengers are there?

In [ ]:
## YOUR SOLUTION HERE
titanic_df.set_index('sex',inplace=True)

## Exercise 14
How do you reset the index?

In [ ]:
## YOUR SOLUTION HERE